### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by AomRerk** [Icyscools/Icyscools#3]
githubมันใช้ยังไงนะ

**Comment by Icyscools** [comment]
Hi, @AomRerk

Thanks for attending to my profile repository and create this nicely question.

For a beginner to learn GitHub, I have a few resources that I recommend for you to learn and try to do along with it.

- [Get started from official](https://docs.github.com/en/get-started/quickstart/hello-world)
- [Amazing tutorial video from freeCodeCamp.org](https://m.youtube.com/watch?v=RGOj5yH7evk)
or see it in [their website](https://www.freecodecamp.org/news/the-beginners-guide-to-git-github/)

I'm strongly recommended that you should practice frequently to make it perfect.

If you have any questions, feel free to ask me in inbox message any times.

Close this for now.
